import os
import json
from typing import Dict, Any, Tuple

def execute(params: Dict[str, Any]) -> Tuple[bool, Dict[str, Any]]:
    """
    Module: TestModule
    
    This module was auto-generated by the Core Builder v2 Assistant.
    
    Args:
        params (Dict[str, Any]): Parameters for the module
            - operation (str): The operation to perform
    
    Returns:
        Tuple[bool, Dict[str, Any]]: Success status and result
    """
    operation = params.get("operation")
    
    if not operation:
        return False, {"error": "Missing required parameter: operation"}
    
    if operation == "hello":
        return True, {"result": "Hello from TestModule!"}
    elif operation == "info":
        return True, {
            "result": {
                "module_name": "TestModule",
                "description": "Auto-generated module for Core Builder v2",
                "version": "0.1.0",
                "created": "2025-05-07 00:49:15"
            }
        }
    else:
        return False, {"error": f"Unknown operation: {operation}"}
